name: Build iOS Tweak
on: 
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Theos
        uses: theos/actions/setup-theos@main

      - name: Build Tweak (.deb)
        run: make package FINALPACKAGE=1

      - name: Upload DEB File
        uses: actions/upload-artifact@v3
        with:
          name: GiamDoHoa-DEB
          path: packages/*.deb
